# Generated by Django 5.2.14 on 2026-09-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="price",
        ),
        migrations.AddField(
            model_name="item",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("lend", "Lend (Free, return needed)"),
                    ("donate", "Donate (Free, keep it)"),
                    ("share", "Share / Common Use"),
                    ("rent", "Rent (Paid, return needed)"),
                ],
                default="donate",
                max_length=10,
                verbose_name="Listing Type",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rent_price_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Only fill this if you are renting the item",
                max_digits=8,
                verbose_name="Rent Price per Day (₹)",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="condition",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Good", "Good"),
                    ("Fair", "Fair"),
                    ("Poor", "Poor"),
                ],
                default="Good",
                max_length=10,
            ),
        ),
    ]
