# Generated by Django 5.2.14 on 2026-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_remove_item_price_item_listing_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price if listing for sale/buy",
                max_digits=8,
                verbose_name="Buy Price (₹)",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("lend", "Lend (Free, return needed)"),
                    ("donate", "Donate (Free, keep it)"),
                    ("share", "Share / Common Use"),
                    ("rent", "Rent (Paid, return needed)"),
                    ("buy", "Buy / Sell (One-time purchase)"),
                ],
                default="donate",
                max_length=10,
                verbose_name="Listing Type",
            ),
        ),
    ]
